In [2]:
import numpy as np

VEC_1 = np.array([-0.25560104, 0.06393334, -0.43760861, 0.35258494, -0.06174621])
VEC_2 = np.array([0.16257878, -0.88344182, 1.14405499, 0.33765161, 1.206262])

manhattan_distance = np.sum(np.abs(VEC_1 - VEC_2))

print(manhattan_distance)

4.23016012


In [3]:
old = np.ones((2, 3), dtype = 'int')
new = old
new[0, :2] = 0
print(old)

[[0 0 1]
 [1 1 1]]


In [4]:
VEC = [-3, 5, 1, 2, 18, 2, 234, 11]

even_entries = [x for x in VEC if x % 2 == 0]

print(even_entries)

[2, 18, 2, 234]


In [5]:
import numpy as np

MAT = np.array([[1.27411064, 0.05188032, -1.27088046],
                [-0.78844599, -0.14775522, -0.28198009]])

average_value = np.mean(MAT)

print(average_value)

-0.1938451333333334


In [6]:
import numpy as np

MAT_1 = np.array([[0.6583596987271446, 1.0128241391924433],
                 [0.37783705753739877, 0.42421340135829255],
                 [-0.6905233695318467, -0.498554227530507]])

MAT_2 = np.array([[0.5045660075993441],
                 [1.83029285141006]])

result = np.dot(MAT_1, MAT_2)

print(result)

[[ 2.18595071]
 [ 0.96707849]
 [-1.26091486]]


In [7]:
import numpy as np

start = 3
end = 10

result = np.arange(start, end + 1)  # +1 to include the 'end' value

print(result)

[ 3  4  5  6  7  8  9 10]


In [8]:
import numpy as np

VEC_1 = np.array([-0.25560104, 0.06393334, -0.43760861, 0.35258494, -0.06174621])
VEC_2 = np.array([0.16257878, -0.88344182, 1.14405499, 0.33765161, 1.206262])

euclidean_distance = np.linalg.norm(VEC_1 - VEC_2)

print(euclidean_distance)

2.27642738170527


In [9]:
import numpy as np

MAT_1 = np.array([[0.6583596987271446, 1.0128241391924433],
                 [0.37783705753739877, 0.42421340135829255],
                 [-0.6905233695318467, -0.498554227530507]])

MAT_2 = np.array([[0.6583596987271446, 1.0128241391924433],
                 [0.37883705753739877, 0.42421340135829255],
                 [-0.6905233695318467, -0.498554227530507]])

are_equal = np.array_equal(MAT_1, MAT_2)

print(are_equal)

False
